#!/bin/bash
:<<__DEF__
Author: morgan@morganism.dev
Date  : Fri Aug  1 17:41:01 PDT 2025
__DEF__
#
#
#
#
echo "debug $DEBUG"
sleep 1

REQUIRED_PACKAGES="git curl ssh"
THIS_DIR=$(dirname $0)
source "$THIS_DIR/functions.sh"

tput smcup # save screen contents
echo "debug $DEBUG"

PACKAGE_LIST=""
if [[ -n "$@" ]]; then
    if [[ -f "$@" ]]; then
        debug "${WHI}Installing: ${BLU} $@${RST}"
        install_packages_in_file "$@"
    fi
fi

debug "Package list is [$PACKAGE_LIST]"
check_packages $REQUIRED_PACKAGES
debug "Package list is  now [$PACKAGE_LIST]"
install_packages "$PACKAGE_LIST"
echo -e "${RST}"
tput rmcup # restore screen contents

set -e
sudo apt update && sudo apt install -y wget
wget -O /tmp/gh.deb https://github.com/cli/cli/releases/download/v2.76.2/gh_2.76.2_linux_amd64.deb
sudo dpkg -i /tmp/gh.deb
sudo apt install -f -y
rm /tmp/gh.deb
echo -e "${BLU}GitHub CLI installed! Version: ${YEL}$(gh --version)${RST}"
echo -e "${BLU}Authenticate now...${RST}"
gh auth login
